commit_message: 'Translate resources in `%original_file_name%` via Crowdin'
pull_request_title: 'Code Quality: Updated translations'
append_commit_message: 
File manager:
  - source: /src/File manager.App/Strings/en-US/*.resw
    translation: /src/File manager.App/Strings/%locale%/%original_file_name%
